name: 'Content-Queue Parse'
description: 'Parse issue contents'
inputs:
  token:
    description: 'GitHub token'
    required: true
  scheduledTitle:
    description: 'Title for scheduling date'
    default: 'Scheduled for'
  timezone:
    description: 'Timezone'
    default: 'Europe/Berlin'
  dateFormat:
    description: 'Date format'
    default: 'YYYY-MM-DD HH:mm'
runs:
  using: 'node12'
  main: 'index.js'
